// Generated by CoffeeScript 1.3.3
(function() {
  var SlideShowManager;

  SlideShowManager = (function() {

    function SlideShowManager() {
      $(document).pitchdeck({
        link_labels: true
      });
    }

    return SlideShowManager;

  })();

  $(document).ready(function() {
    return new SlideShowManager;
  });

}).call(this);
